name: Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bypass env error
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          echo DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} >> .env
          cat .env
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test
